/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.usluga;

import controller.ClientController;
import domain.NapomenaZaUslugu;
import domain.Usluga;
import domain.VrstaUsluge;
import form.napomena.UnosNapomene;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import models.napomena.TableModelNapomene;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ivana
 */
public class DetaljiUsluge extends javax.swing.JFrame {

    /**
     * Creates new form DetaljiUsluge
     */
    private PretragaUsluge pretragaUsluge;
    private Usluga usluga;
    private List<NapomenaZaUslugu> napomene;

    public DetaljiUsluge(Usluga usluga, List<NapomenaZaUslugu> napomene, PretragaUsluge pretragaUsluge) {
        try {
            initComponents();

            this.usluga = usluga;
            this.napomene = napomene;
            this.pretragaUsluge = pretragaUsluge;

            lblSifraUsluge.setText(String.valueOf(usluga.getSifraUsluge()));
            txtNaziv.setText(usluga.getNazivUsluge());
            txtCena.setText(String.valueOf(usluga.getCenaUsluge()));
            txtTrajanje.setText(String.valueOf(usluga.getTrajanjeUsluge()));

            popuniComboVrstaUsluge();
            cbVrstaUsluge.setSelectedItem(usluga.getVrstaUsluge());

            TableModelNapomene model = new TableModelNapomene(napomene);
            tblNapomena.setModel(model);

            setLocationRelativeTo(null);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (Exception ex) {
            Logger.getLogger(DetaljiUsluge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTrajanje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbVrstaUsluge = new javax.swing.JComboBox();
        btnSacuvajUslugu = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblSifraUsluge = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNapomena = new javax.swing.JTable();
        btnDodajNapomenu = new javax.swing.JButton();
        btnObrisiNapomenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalji Usluge");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Naziv:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cena:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Trajanje:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Vrsta usluge:");

        btnSacuvajUslugu.setBackground(new java.awt.Color(153, 153, 255));
        btnSacuvajUslugu.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajUslugu.setText("Sačuvaj izmene");
        btnSacuvajUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajUsluguActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(255, 153, 153));
        btnObrisi.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisi.setText("Obrisi uslugu");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sifra usluge:");

        lblSifraUsluge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Napomene za uslugu"));

        tblNapomena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNapomena);

        btnDodajNapomenu.setBackground(new java.awt.Color(153, 153, 255));
        btnDodajNapomenu.setForeground(new java.awt.Color(255, 255, 255));
        btnDodajNapomenu.setText("Dodaj napomenu za uslugu");
        btnDodajNapomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNapomenuActionPerformed(evt);
            }
        });

        btnObrisiNapomenu.setBackground(new java.awt.Color(255, 102, 102));
        btnObrisiNapomenu.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisiNapomenu.setText("Obriši napomenu za uslugu");
        btnObrisiNapomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiNapomenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnDodajNapomenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiNapomenu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajNapomenu)
                    .addComponent(btnObrisiNapomenu))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(190, 190, 190))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtCena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTrajanje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSifraUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(cbVrstaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnObrisi)
                        .addGap(51, 51, 51)
                        .addComponent(btnSacuvajUslugu)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblSifraUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVrstaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnSacuvajUslugu))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNapomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNapomenuActionPerformed
        try {

            UnosNapomene formaNapomena = new UnosNapomene();
            formaNapomena.setVisible(true);

            formaNapomena.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    List<NapomenaZaUslugu> privremeneNapomene = formaNapomena.getPrivremeneNapomene();
                    napomene.addAll(privremeneNapomene);
                    TableModelNapomene model = new TableModelNapomene(napomene);
                    tblNapomena.setModel(model);
                    ((AbstractTableModel) tblNapomena.getModel()).fireTableDataChanged();
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(KreiranjeUsluge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajNapomenuActionPerformed

    private void btnObrisiNapomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiNapomenuActionPerformed
        int red = tblNapomena.getSelectedRow();
        if (red != -1) {
            NapomenaZaUslugu oznacenaNapomena = napomene.get(red);
            napomene.remove(oznacenaNapomena);
            TableModelNapomene model = new TableModelNapomene(napomene);
            tblNapomena.setModel(model);
            ((AbstractTableModel) tblNapomena.getModel()).fireTableDataChanged();
        }
    }//GEN-LAST:event_btnObrisiNapomenuActionPerformed

    private void btnSacuvajUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajUsluguActionPerformed
        try {
            String naziv = txtNaziv.getText();
            double cena = Double.parseDouble(txtCena.getText());
            int trajanje = Integer.parseInt(txtTrajanje.getText());
            VrstaUsluge vrstaUsluge = (VrstaUsluge) cbVrstaUsluge.getSelectedItem();
            TableModelNapomene tmn = (TableModelNapomene) tblNapomena.getModel();
            List<NapomenaZaUslugu> listaNapomena = tmn.getLista();

            usluga.setNazivUsluge(naziv);
            usluga.setCenaUsluge(cena);
            usluga.setTrajanjeUsluge(trajanje);
            usluga.setVrstaUsluge(vrstaUsluge);
            usluga.setNapomene(listaNapomena);

            ClientController.getInstance().updateUsluga(usluga);
            JOptionPane.showMessageDialog(this, "Sistem je uspešno izmenio uslugu.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            pretragaUsluge.refreshTable();
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni uslugu. Pokušajte ponovo!", "Greška", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(KreiranjeUsluge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajUsluguActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            controller.ClientController.getInstance().deleteUsluga(usluga);
            JOptionPane.showMessageDialog(this, "Sistem je uspešno obrisao uslugu");
            pretragaUsluge.refreshTable();
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše uslugu. Pokušajte ponovo!", "Greška", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNapomenu;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiNapomenu;
    private javax.swing.JButton btnSacuvajUslugu;
    private javax.swing.JComboBox cbVrstaUsluge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSifraUsluge;
    private javax.swing.JTable tblNapomena;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtTrajanje;
    // End of variables declaration//GEN-END:variables

    private void popuniComboVrstaUsluge() throws Exception {
        List<VrstaUsluge> listaVrstaUsluge = controller.ClientController.getInstance().getListVrstaUsluge();
        for (VrstaUsluge vrstaUsluge : listaVrstaUsluge) {
            cbVrstaUsluge.addItem(vrstaUsluge);
        }
    }

}
