/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.klijent;

import controller.ClientController;
import domain.Klijent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import models.klijent.TableModelKlijenti;

/**
 *
 * @author Ivana
 */
public class PretragaKlijentaForm extends javax.swing.JDialog {

     public PretragaKlijentaForm(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        popuniTabeluKlijenata();
    }

    @Override
    public void dispose() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDetaljiKlijenta = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga klijenta");

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Pretraga (Ime/Prezime):");

        btnDetaljiKlijenta.setBackground(new java.awt.Color(153, 153, 255));
        btnDetaljiKlijenta.setForeground(new java.awt.Color(255, 255, 255));
        btnDetaljiKlijenta.setText("Detalji klijenta");
        btnDetaljiKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiKlijentaActionPerformed(evt);
            }
        });

        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });

        btnPretrazi.setBackground(new java.awt.Color(153, 153, 255));
        btnPretrazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetaljiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetaljiKlijenta)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetaljiKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiKlijentaActionPerformed
        TableModelKlijenti tnm = (TableModelKlijenti) tblKlijenti.getModel();
        int red = tblKlijenti.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Molim Vas selektujte red!");
        } else {
            int modelRed = tblKlijenti.convertRowIndexToModel(red);
            Klijent k = tnm.vratiNaOsnovuReda(modelRed);
            JOptionPane.showMessageDialog(this, "Sistem je učitao klijenta!", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

            try {
                new DetaljiKlijenta(k).setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita klijenta!", "Greška", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(PretragaKlijentaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnDetaljiKlijentaActionPerformed

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
    
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
      String pretraga = txtPretraga.getText().trim().toLowerCase();
    try {
        List<Klijent> listaKlijenata = ClientController.getInstance().getListKlijent();

        String[] pretragaDeliovi = pretraga.split("\\s+");
        List<Klijent> filtriraniKlijenti;

        if (pretragaDeliovi.length == 2) {
            String ime = pretragaDeliovi[0];
            String prezime = pretragaDeliovi[1];

            filtriraniKlijenti = listaKlijenata.stream()
                .filter(k -> k.getIme().toLowerCase().contains(ime) && k.getPrezime().toLowerCase().contains(prezime))
                .toList();
        } else {
            filtriraniKlijenti = listaKlijenata.stream()
                .filter(k -> k.getIme().toLowerCase().contains(pretraga) || k.getPrezime().toLowerCase().contains(pretraga))
                .toList();
        }

        if (!filtriraniKlijenti.isEmpty()) {
            TableModelKlijenti model = new TableModelKlijenti(filtriraniKlijenti);
            tblKlijenti.setModel(model);
            JOptionPane.showMessageDialog(this, "Sistem je pronašao klijente na osnovu unete vrednosti!", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nadje klijente po zadatom kriterijumu", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Sistem ne može da nadje klijente po zadatom kriterijumu ", "Greška", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnPretraziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetaljiKlijenta;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluKlijenata() {
        try {
            List<Klijent> listaKlijenta = ClientController.getInstance().getListKlijent();
            TableModelKlijenti model = new TableModelKlijenti(listaKlijenta);
            tblKlijenti.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(PretragaKlijentaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
